package eu.europa.ec.isa2.restapi.profile.enums;

public enum MessagingEndpointType {
    GET_MESSAGE,
    GET_MESSAGE_REFERENCE_LIST,
    GET_RESPONSE_MESSAGE,
    GET_RESPONSE_MESSAGE_REFERENCE_LIST,
    SUBMIT_MESSAGE_SYNC,
    SUBMIT_MESSAGE_ASYNC,
    SUBMIT_RESPONSE_MESSAGE,
    SUBMIT_RESPONSE_MESSAGE_WEBHOOK,
    SUBMIT_SIGNAL,
    SUBMIT_SIGNAL_WEBHOOK;
}
